service: uploadimgtos3

frameworkVersion: '2'

custom:
  bucket: upload-img-bucket
  
# provider:
#   name: aws
#   runtime: nodejs12.x
#   iamRoleStatements:
#     - Effect: Allow
#       Action:
#         - s3:*
#       Resource: "*"
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    BUCKET_NAME: ${self:custom.bucket}
    DB_HOSTNAME:
      Fn::GetAtt:
        - DBInstance
        - Endpoint.Address
    DB_PORT:
      Fn::GetAtt:
        - DBInstance
        - Endpoint.Port
    DB_NAME: '${self:service}_${self:provider.stage}_db'
    DB_USERNAME: 'userpost'
    DB_PASSWORD: '1234567890'
    COGNITO_USER_POOL_ID:
      Ref: UserPool
    COGNITO_CLIENT_ID: 
      Ref: UserPoolClient

package:
  individually: true
  exclude:
    - '*'
    - '**/*'

functions:
  signup:
    handler: 'signup.handler'
    package:
      include:
        - signup.js
        - node_modules/**
    events:
      - http:
          path: signup
          method: post
  signin:
    handler: 'signin.handler'
    package:
      include:
        - signin.js
    events:
      - http:
          path: signin
          method: post
  getImgs:
    handler: 'getImgs.handler'
    package:
      include:
        - getImgs.js
        - node_modules/**
    events:
      - http:
          path: image/getAll
          method: get
  post:
    handler: 'post.handler'
    package:
      include:
        - post.js
        - node_modules/**
    events:
      - http:
          path: image/post
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  getPresignedPostData:
    handler: 'getPresignedPostData.handler'
    package:
      include:
        - getPresignedPostData.js
        - node_modules/**
    events:
      - http:
          path: getPresignedPostData
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  deleteImg:
    handler: 'deleteImg.handler'
    package:
      include:
        - deleteImg.js
        - node_modules/**
    events:
      - http:
          path: image/delete
          method: delete
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  getUsers:
    handler: 'getUsers.handler'
    package:
      include:
        - getUsers.js
        - node_modules/**
    events:
      - http:
          path: users/getAll
          method: get
  deleteUser:
    handler: 'deleteUser.handler'
    package:
      include:
        - deleteUser.js
        - node_modules/**
    events:
      - http:
          path: users/delete
          method: delete          

resources:
  - ${file(resources/cognito.yml)}
  - ${file(resources/rds.yml)}
