service: upload-imgs-to-S3

frameworkVersion: '2'

custom:
  bucket: upload-img-bucket
  
# provider:
#   name: aws
#   runtime: nodejs12.x
#   iamRoleStatements:
#     - Effect: Allow
#       Action:
#         - s3:*
#       Resource: "*"
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    DB_HOSTNAME:
      Fn::GetAtt:
        - DBInstance
        - Endpoint.Address
    DB_PORT:
      Fn::GetAtt:
        - DBInstance
        - Endpoint.Port
    DB_NAME: '${self:service}_${self:provider.stage}_db'
    DB_USERNAME: 'userpost'
    DB_PASSWORD: '1234567890'
    COGNITO_USER_POOL_ID:
      Ref: UserPool
    COGNITO_CLIENT_ID: 
      Ref: UserPoolClient

package:
  individually: true
  exclude:
    - '*'
    - '**/*'
    
# functions:
#   postprocess:
#     handler: handler.postprocess
#     events:
#       - s3:
#           bucket: ${self:custom.bucket}
#           event: s3:ObjectCreated:*
#           rules:
#             - suffix: .png

functions:
  signup:
    handler: 'signup.handler'
    package:
      include:
        - signup.js
    events:
      - http:
          path: signup
          method: post
  signin:
    handler: 'signin.handler'
    package:
      include:
        - signin.js
    events:
      - http:
          path: signin
          method: post
  getImgs:
    handler: 'getImgs.handler'
    package:
      include:
        - getImgs.js
        - node_modules/**
    events:
      - http:
          path: getImgs
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  post:
    handler: 'post.handler'
    package:
      include:
        - post.js
        - node_modules/**
    events:
      - http:
          path: post
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  - ${file(resources/cognito.yml)}
  - ${file(resources/rds.yml)}
